#!/usr/bin/env ruby.exe
require 'pg'
conn = PGconn.open(:dbname => 'production')
conn.exec('delete from tv_shows')
conn.exec('delete from tv_seasons')
conn.exec('delete from tv_episodes')

conn.close()

