#!/usr/bin/env ruby.exe
require 'pg'
require 'date'
conn = PGconn.open(:dbname => 'production')

isTVshow = false
e = '  '

File.open('db/movies.list', 'r') do |f|
  while (not f.eof?)
  	if isTVshow
  		a = e
  	else
  		a = f.readline
  	end
	if /\d{4,}\-\d{4,5}$/ =~ a || /\d{4,}\-\?{4,5}$/ =~ a #if matches tv show
	  	tString = /^".{1,}"/.match(a)[0]
	  	title = (tString[1,tString.length-2].gsub("'","\'"))
	  	valid_title = title.unpack('C*').pack('U*')

	    query,y1,y2 = ''
	    y1 = Date::strptime(/\d{4,}\-\S{4,5}$/.match(a)[0].split("-").first, "%Y").to_s

	    if /\d{4,}\-\d{4,5}$/ =~ a
	    	y2 = Date::strptime(/\d{4,}\-\d{4,5}$/.match(a)[0].split("-").last, "%Y").to_s
	    	#puts "inserting date"
	    	puts "TV SHOW 1: "+valid_title+" y1:"+y1
		    conn.exec('INSERT INTO tv_shows (id,title,year_released,year_ended) VALUES (DEFAULT,$1,$2,$3)',[valid_title,y1,y2])
	    else
	    	#puts "inserting no date"
	    	puts "TV SHOW 2: "+valid_title+" y1:"+y1
		    conn.exec('INSERT INTO tv_shows (id,title,year_released) VALUES (DEFAULT,$1,$2)',[valid_title,y1])
	    end

    	while (not f.eof) #now loop through episodes
	    	e = f.readline
	    	if /\d{4,}\-\d{4,5}$/ =~ e || /\d{4,}\-\?{4,5}$/ =~ e #is it a show? 
	    		# puts "breaking out of "+e
	    		isTVshow = true
	    		break
	    	else
				# puts "EPISODE: "+e
				isTVshow = false
	    	end

		  	tvString = /^".{1,}"/.match(e)[0]
		  	valid_tv_title = (tvString[1,tvString.length-2].gsub("'","\'\'")).unpack('C*').pack('U*')

	    	if /{.{1,}(#.{1,}\..{1,})}/ =~ e #is numbered
		    	epSeason = /\d{1,}\.\d{1,}/.match(e)[0].split(".").first
		    	epNumber = /\d{1,}\.\d{1,}/.match(e)[0].split(".").last
		    	epTitleString = /{.{1,}(#)/.match(e)[0]
		    	hasNoNumber = false
	   		elsif /{.{1,}}/ =~ e #has title braces
	   			epSeason = '0'
	   			epNumber = '0'
	   			epTitleString = /{.{1,}}/.match(e)[0] 
	   			hasNoNumber = true
	   		else
	   			epTitleString = ''
	   		end

	   		if epTitleString.length > 250
	   			valid_ep_title = (epTitleString[1,250].gsub("'","\'")).unpack('C*').pack('U*')
	   		elsif epTitleString.length > 4 and !hasNoNumber
	   			valid_ep_title = (epTitleString[1,epTitleString.length-4].gsub("'","\'")).unpack('C*').pack('U*')
	   		elsif epTitleString.length > 4 and hasNoNumber
	   			valid_ep_title = (epTitleString[1,epTitleString.length-2].gsub("'","\'")).unpack('C*').pack('U*')
	   		else
	   			valid_ep_title = ''
	   		end

	   		skip = false

	   		if (/\((\d{1,})\)/) =~ e #has tv year 
		    	tvYearMatch = /\((\d{1,})\)/.match(e)[0]
		    	tvYear = Date::strptime(tvYearMatch[1,tvYearMatch.length-2], "%Y").to_s
		    else #if episode doesn't have a tv year, skip because not possible to find tv show
		    	skip = true
		    end

		    if !skip 
		    	#puts "valid_tv_title: "+valid_tv_title
		    	#puts "valid_ep_title: "+valid_ep_title
		    	#puts "epSeason: "+epSeason
		    	#puts "epNumber: "+epNumber
		    	#puts "tvYear: "+tvYear

		    	query = 'SELECT id FROM tv_shows where title = \''+valid_tv_title+'\' and year_released = \''+tvYear+'\';'
		    	#puts "QUERY: "+query
		    	tvshows = conn.exec(query)
		    	# tvshowID = conn.exec('SELECT id FROM tv_shows where title = $1 and year_released = $2',[valid_tv_title,tvYear]).getvalue(0,0)
			    if tvshows.num_tuples > 0
				    tvshowID = tvshows.getvalue(0,0)

				    tvseason = conn.exec('SELECT id from tv_seasons where tv_show_id = $1 and number = $2',[tvshowID,epSeason])

					if tvseason == nil or tvseason == 0 or tvseason.num_tuples.zero? #season does not exist so create season
					    conn.exec('INSERT INTO tv_seasons (id,tv_show_id,number) VALUES  
				    			(DEFAULT,$1,$2);',[tvshowID,epSeason])
					end
					tvseasonID = conn.exec('SELECT id from tv_seasons where tv_show_id = $1 and number = $2',[tvshowID,epSeason]).getvalue(0,0) 

			    	if (/\d{4,5}$/) =~ e #ep has year
				    	epYear = Date::strptime(/\d{4,5}$/.match(e)[0], "%Y").to_s
				    	#puts "epYear: "+epYear
				    	#puts "Insert ep1: "+valid_ep_title
				    	conn.exec('INSERT INTO tv_episodes (id,number,title,tv_season_id,air_date) VALUES 
			    			(DEFAULT,$1,$2,$3,$4)',[epNumber,valid_ep_title,tvseasonID,epYear])
				    else #ep has no year
				    	#puts "Insert ep2: "+valid_ep_title
				    	conn.exec('INSERT INTO tv_episodes (id,number,title,tv_season_id) VALUES 
			    			(DEFAULT,$1,$2,$3)',[epNumber,valid_ep_title,tvseasonID])
				    end
				end
			end
	    end
	  end
  end 
end 

#res.each do |row|
 # row.each do |column|
 #  puts column
 # end
#end

conn.close()
puts "end of file!"